site_name: Embedded Security
theme: 
   name: material
   features:
      -  search.suggest
      -  search.highlight
      -  content.tabs.link
   plugins:
     - search
   palette: 
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
- Home  : "https://embeddednext.github.io/mindset"
- Elite :
  - Levels of Mindset : "1mindset.md"
  - Levels of Discipline : "2discipline.md"
  - Levels of Business Growth : "3business.md"
  - Levels of Freedom : "4freedom.md"
